In [1]:
from time import sleep
from tqdm import tqdm

import numpy as np
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
from google.oauth2.service_account import Credentials

from keys import GOOG_API_KEY

In [2]:
## Load dataframes
# Polling averages
pres = pd.read_csv('averages/presidential_gen_approval.csv')
pres_issue = pd.read_csv('averages/presidential_issue_approvals.csv')
pres_rv = pd.read_csv('averages/presidential_RV_approval.csv')
generic_ballot = pd.read_csv('averages/generic_ballot.csv')

# Polls display tables
pres_polls = pd.read_csv('transformed_tables/gen_approval_polls.csv')
issue_polls = pd.read_csv('transformed_tables/issue_approval_polls.csv')
gb_polls = pd.read_csv('transformed_tables/generic_ballot_polls_disp.csv')

In [3]:
# Define the scope
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

# Authenticate with the service account
credentials = Credentials.from_service_account_file(
    GOOG_API_KEY,
    scopes=scopes
)

# Authorize gspread
client = gspread.authorize(credentials)

## Polling Averages

In [4]:
spreadsheet = client.open("snoutcounter-data")
worksheet = spreadsheet.worksheet("approval-stats")
worksheet.clear()

set_with_dataframe(worksheet, pres.reset_index())

In [5]:
worksheet = spreadsheet.worksheet("approval_stats_RV")
worksheet.clear()

set_with_dataframe(worksheet, pres_rv.reset_index())

In [6]:
issues = ['economy', 'immigration', 'inflation', 'trade_tariffs', 'foreign_policy', 'healthcare', 'crime']
issue_suffixes = ['econ', 'imm', 'infl', 'trade', 'fp', 'healthcare', 'crime']

for iss, suf in tqdm(zip(issues, issue_suffixes)):
    worksheet = spreadsheet.worksheet(f"approval_stats_{suf}")
    worksheet.clear()

    issue_df = pres_issue[pres_issue['issue'] == iss]
    set_with_dataframe(worksheet, issue_df.reset_index())

7it [00:06,  1.06it/s]

In [7]:
## Net issue approval
net_issues = pd.pivot_table(pres_issue[pres_issue['issue'].isin(issues)], 
                            values=['net', 'net_lower_ci', 'net_upper_ci'], index=['end_date'], columns=['issue'],
                           aggfunc="first").reset_index()
net_issues.columns = ['_'.join(col).strip() for col in net_issues.columns.values]
net_issues.head()

,end_date_,net_crime,net_economy,net_foreign_policy,net_healthcare,net_immigration,net_inflation,net_trade_tariffs,net_lower_ci_crime,net_lower_ci_economy,...,net_lower_ci_immigration,net_lower_ci_inflation,net_lower_ci_trade_tariffs,net_upper_ci_crime,net_upper_ci_economy,net_upper_ci_foreign_policy,net_upper_ci_healthcare,net_upper_ci_immigration,net_upper_ci_inflation,net_upper_ci_trade_tariffs
0,2025-01-21,0.0,7.401667,3.401667,0.00000,9.401667,-4.598333,-0.598333,0.0,7.401667,...,9.401667,-4.598333,-0.598333,0.0,7.401667,3.401667,0.00000,9.401667,-4.598333,-0.598333
1,2025-01-22,0.0,7.401667,3.401667,0.00000,9.401667,-4.598333,-0.598333,0.0,7.401667,...,9.401667,-4.598333,-0.598333,0.0,7.401667,3.401667,0.00000,9.401667,-4.598333,-0.598333
2,2025-01-23,0.0,0.609089,3.401667,-16.11471,1.181534,-4.598333,-0.598333,0.0,-7.821559,...,-9.020933,-4.598333,-0.598333,0.0,9.039737,3.401667,-16.11471,11.384000,-4.598333,-0.598333
3,2025-01-24,0.0,0.609089,3.401667,-16.11471,1.181534,-4.598333,-0.598333,0.0,-7.821559,...,-9.020933,-4.598333,-0.598333,0.0,9.039737,3.401667,-16.11471,11.384000,-4.598333,-0.598333
4,2025-01-25,0.0,0.609089,3.401667,-16.11471,1.181534,-4.598333,-0.598333,0.0,-7.821559,...,-9.020933,-4.598333,-0.598333,0.0,9.039737,3.401667,-16.11471,11.384000,-4.598333,-0.598333

In [8]:
worksheet = spreadsheet.worksheet("net_approval_issues")
worksheet.clear()

set_with_dataframe(worksheet, net_issues.reset_index())

In [9]:
worksheet = spreadsheet.worksheet("generic_ballot_stats")
worksheet.clear()

set_with_dataframe(worksheet, generic_ballot.reset_index())

## Polls Display Tables

In [10]:
pres_polls['sponsors'] = '^Sponsor: ' + pres_polls['sponsors'] + '^'
pres_polls['sponsors'] = pres_polls['sponsors'].fillna('')
pres_polls['partisan'] = pres_polls['partisan'].replace({
    'DEM': ' (D)',
    'REP': ' (R)',
    'WFP': ' (WF)'
}).fillna('')
pres_polls = pres_polls.sort_values(['total_weight'], ascending=False)
pres_polls = pres_polls.rename({
    'pollster':'Pollster', 'approve':'Approve', 'disapprove':'Disapprove', 'net':'Net', 
    'total_weight':'Weight', 'start_date':'Start Date', 'end_date':'End Date', 'url':'URL', 'adj_net':'Adjusted Net'}, axis='columns')
pres_polls['Sample'] = pres_polls['sample_size'].astype(int).astype(str) + ' ' + pres_polls['population']
pres_polls['Start Date'] = pd.to_datetime(pres_polls['Start Date']).astype(str)
pres_polls['End Date'] = pres_polls['End Date'].astype(str)
pres_polls = pres_polls.reset_index()
pres_polls['Pollster'] = ('<a href="' + pres_polls['URL'] + '" style="color:black; text-decoration:underline;"><u>' + 
                          pres_polls['Pollster'] + pres_polls['partisan'] + '</u></a>' + pres_polls['sponsors'])
pres_polls = pres_polls[['Pollster', 'Start Date', 'End Date', 'Sample', 'Weight', 'Approve', 'Disapprove', 'Net', 'Adjusted Net']]
pres_polls

,Pollster,Start Date,End Date,Sample,Weight,Approve,Disapprove,Net,Adjusted Net
0,"<a href=""https://echeloninsights.com/in-the-ne...",2026-02-19,2026-02-23,1002 LV,9.607037e-02,44.0,55.0,-11.0,-13.703202
1,"<a href=""https://www.reuters.com/world/us/most...",2026-02-18,2026-02-23,4638 A,9.286707e-02,40.0,58.0,-18.0,-13.979505
2,"<a href=""https://emersoncollegepolling.com/feb...",2026-02-21,2026-02-22,1000 LV,8.743387e-02,42.7,54.7,-12.0,-17.872802
3,"<a href=""https://navigatorresearch.org/views-o...",2026-02-19,2026-02-23,1000 RV,5.582034e-02,41.0,58.0,-17.0,-16.090672
4,"<a href=""https://www.cnn.com/2026/02/23/politi...",2026-02-17,2026-02-20,2496 A,5.420672e-02,36.0,63.0,-27.0,-18.962703
...,...,...,...,...,...,...,...,...,...
610,"<a href=""https://mclaughlinonline.com/pols/wp-...",2025-01-22,2025-01-27,1000 LV,1.683264e-21,52.0,43.0,9.0,5.138296
611,"<a href=""https://substack.com/inbox/post/15539...",2025-01-21,2025-01-21,742 A,1.300770e-21,49.0,36.0,13.0,8.572285
612,"<a href=""https://quantusinsights.org/f/februar...",2025-02-01,2025-02-03,1000 RV,1.243624e-21,51.9,45.3,6.6,0.243135
613,"<a href=""https://www.ipsos.com/en-us/reuters-i...",2025-01-20,2025-01-21,1077 A,1.225612e-21,47.0,41.0,6.0,10.020495
614,"<a href=""https://quantusinsights.org/f/trump%E...",2025-01-22,2025-01-23,1000 RV,3.722886e-22,54.0,40.0,14.0,7.643135

In [11]:
worksheet = spreadsheet.worksheet("polls_display_table")
worksheet.clear()

set_with_dataframe(worksheet, pres_polls)

In [12]:
issue_polls['sponsor'] = '^Sponsor: ' + issue_polls['sponsor'] + '^'
issue_polls['sponsor'] = issue_polls['sponsor'].fillna('')
issue_polls = issue_polls.sort_values(['issue', 'total_weight'], ascending=[True, False])
issue_polls = issue_polls.rename({
    'pollster':'Pollster', 'approve':'Approve', 'disapprove':'Disapprove', 'net':'Net', 
    'total_weight':'Weight', 'start_date':'Start Date', 'end_date':'End Date', 'url':'URL', 'adj_net':'Adjusted Net',
    'issue':'Issue'}, axis='columns')
issue_polls['Sample'] = issue_polls['sample_size'].astype(int).astype(str) + ' ' + issue_polls['population']
issue_polls['Start Date'] = pd.to_datetime(issue_polls['Start Date']).astype(str)
issue_polls['End Date'] = issue_polls['End Date'].astype(str)
issue_polls = issue_polls.reset_index()
issue_polls['Pollster'] = ('<a href="' + issue_polls['URL'] + '" style="color:black; text-decoration:underline;"><u>' + 
                          issue_polls['Pollster'] + '</u></a>' + issue_polls['sponsor'])
issue_polls = issue_polls[issue_polls['Issue'].isin(issues)]
issue_polls['Issue'] = issue_polls['Issue'].replace({
    'economy': 'Economy',
    'immigration': 'Immigration',
    'foreign_policy': 'Foreign policy',
    'inflation': 'Inflation/prices',
    'trade_tariffs': 'Trade/tariffs',
    'healthcare': 'Healthcare',
    'crime': 'Crime'
})
issue_polls = issue_polls[['Pollster', 'Start Date', 'End Date', 'Issue', 'Sample', 'Weight', 'Approve', 'Disapprove', 'Net', 'Adjusted Net']]
issue_polls

,Pollster,Start Date,End Date,Issue,Sample,Weight,Approve,Disapprove,Net,Adjusted Net
0,"<a href=""https://napolitannews.org/posts/trump...",2026-02-18,2026-02-19,Crime,1000 RV,1.561234e-02,47.0,49.0,-2.0,-10.501695
1,"<a href=""https://d3nkl3psvxxpe9.cloudfront.net...",2026-02-13,2026-02-16,Crime,1682 A,9.640832e-03,43.0,47.0,-4.0,-6.793196
2,"<a href=""https://johnzogbystrategies.com/the-p...",2026-02-04,2026-02-05,Crime,1000 LV,4.691381e-03,46.0,50.0,-4.0,-12.460567
3,"<a href=""https://www.gelliottmorris.com/p/ahea...",2026-02-18,2026-02-20,Crime,1566 A,4.573651e-03,41.0,53.0,-12.0,-11.848599
4,"<a href=""https://harvardharrispoll.com/wp-cont...",2026-01-28,2026-01-29,Crime,2000 RV,3.479487e-03,47.0,47.0,0.0,-8.262434
...,...,...,...,...,...,...,...,...,...,...
1197,"<a href=""https://pro.morningconsult.com/tracke...",2025-02-07,2025-02-09,Trade/tariffs,22305 RV,1.592050e-15,47.0,43.0,4.0,-9.936044
1198,"<a href=""https://www.dataforprogress.org/memos...",2025-01-31,2025-02-02,Trade/tariffs,1205 LV,8.123777e-16,42.0,46.0,-4.0,-10.103553
1199,"<a href=""https://pro.morningconsult.com/tracke...",2025-01-31,2025-02-03,Trade/tariffs,2303 RV,6.817400e-16,48.0,40.0,8.0,-5.936044
1200,"<a href=""https://pro.morningconsult.com/tracke...",2025-01-24,2025-01-26,Trade/tariffs,2302 RV,3.688568e-16,50.0,37.0,13.0,-0.936044
1201,"<a href=""https://www.ipsos.com/en-us/reuters-i...",2025-01-20,2025-01-21,Trade/tariffs,1077 A,2.154706e-16,38.0,40.0,-2.0,-0.598333

In [13]:
worksheet = spreadsheet.worksheet("polls_display_issues")
worksheet.clear()

set_with_dataframe(worksheet, issue_polls)

In [14]:
gb_polls['sponsors'] = '^Sponsor: ' + gb_polls['sponsors'] + '^'
gb_polls['partisan'] = gb_polls['partisan'].replace({
    'DEM': ' (D)',
    'REP': ' (R)',
    'WFP': ' (WF)'
}).fillna('')
gb_polls['sponsors'] = gb_polls['sponsors'].fillna('')
gb_polls = gb_polls.sort_values(['total_weight'], ascending=False)
gb_polls = gb_polls.rename({
    'pollster':'Pollster', 'dem':'Democrats', 'rep':'Republicans', 'net':'Net', 
    'total_weight':'Weight', 'start_date':'Start Date', 'end_date':'End Date', 'url':'URL', 'adj_net':'Adjusted Net'}, axis='columns')
gb_polls['Sample'] = gb_polls['sample_size'].astype(int).astype(str) + ' ' + gb_polls['population']
gb_polls['Start Date'] = pd.to_datetime(gb_polls['Start Date']).astype(str)
gb_polls['End Date'] = gb_polls['End Date'].astype(str)
gb_polls = gb_polls.reset_index()
gb_polls['Pollster'] = ('<a href="' + gb_polls['URL'] + '" style="color:black; text-decoration:underline;"><u>' + 
                          gb_polls['Pollster'] + gb_polls['partisan'] + '</u></a>' + gb_polls['sponsors'])
gb_polls = gb_polls[['Pollster', 'Start Date', 'End Date', 'Sample', 'Weight', 'Democrats', 'Republicans', 'Net', 'Adjusted Net']]
gb_polls

,Pollster,Start Date,End Date,Sample,Weight,Democrats,Republicans,Net,Adjusted Net
0,"<a href=""https://echeloninsights.com/in-the-ne...",2026-02-19,2026-02-23,1002 LV,1.458716e-01,50.0,46.0,-4.0,-6.025567
1,"<a href=""https://emersoncollegepolling.com/feb...",2026-02-21,2026-02-22,1000 LV,1.327581e-01,50.4,42.4,-8.0,-8.501803
2,"<a href=""https://www.reuters.com/world/us/most...",2026-02-18,2026-02-23,3686 RV,1.257058e-01,40.0,38.0,-2.0,-4.266619
3,"<a href=""https://today.yougov.com/politics/art...",2026-02-20,2026-02-23,1402 RV,6.227720e-02,45.0,41.0,-4.0,-3.969967
4,"<a href=""https://pro.morningconsult.com/tracke...",2026-02-20,2026-02-22,2202 RV,5.209959e-02,46.0,42.0,-4.0,-6.199824
...,...,...,...,...,...,...,...,...,...
313,"<a href=""https://napolitannews.org/posts/gener...",2025-01-15,2025-01-16,1000 RV,1.945246e-21,44.0,51.0,7.0,3.287892
314,"<a href=""https://mclaughlinonline.com/pols/wp-...",2025-01-22,2025-01-27,1000 LV,1.475614e-21,40.0,48.0,8.0,2.865777
315,"<a href=""https://quantusinsights.org/f/trump%E...",2025-01-22,2025-01-23,1000 RV,7.297688e-22,45.0,48.0,3.0,1.936794
316,"<a href=""https://www.cygn.al/poll-musk-most-ef...",2024-12-09,2024-12-11,1500 LV,5.660332e-23,44.6,48.4,3.8,2.684563
317,"<a href=""https://mclaughlinonline.com/2024/12/...",2024-12-11,2024-12-16,1000 LV,1.436257e-23,42.0,47.0,5.0,-0.134223

In [15]:
worksheet = spreadsheet.worksheet("generic_ballot_polls_display_table")
worksheet.clear()

set_with_dataframe(worksheet, gb_polls)