In [104]:
from time import sleep
from tqdm import tqdm

import numpy as np
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
from google.oauth2.service_account import Credentials

import plotly.express as px
import plotly.graph_objects as go

from keys import GOOG_API_KEY

In [105]:
## Load dataframes
# Polling averages
pres = pd.read_csv('averages/presidential_gen_approval.csv')
pres_issue = pd.read_csv('averages/presidential_issue_approvals.csv')
pres_rv = pd.read_csv('averages/presidential_RV_approval.csv')
generic_ballot = pd.read_csv('averages/generic_ballot.csv')
ca_gov_primary = pd.read_csv('averages/ca_governor_primary_2026.csv')

# Polls display tables
pres_polls = pd.read_csv('transformed_tables/gen_approval_polls.csv')
issue_polls = pd.read_csv('transformed_tables/issue_approval_polls.csv')
gb_polls = pd.read_csv('transformed_tables/generic_ballot_polls_disp.csv')
ca_gov_polls = pd.read_csv('transformed_tables/ca_gov_primary_2026_transf.csv')

In [106]:
# Define the scope
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

# Authenticate with the service account
credentials = Credentials.from_service_account_file(
    GOOG_API_KEY,
    scopes=scopes
)

# Authorize gspread
client = gspread.authorize(credentials)

## Polling Averages

In [107]:
spreadsheet = client.open("snoutcounter-data")
worksheet = spreadsheet.worksheet("approval-stats")
worksheet.clear()

set_with_dataframe(worksheet, pres.reset_index())

In [108]:
worksheet = spreadsheet.worksheet("approval_stats_RV")
worksheet.clear()

set_with_dataframe(worksheet, pres_rv.reset_index())

In [109]:
issues = ['economy', 'immigration', 'inflation', 'trade_tariffs', 'foreign_policy', 'healthcare', 'crime']
issue_suffixes = ['econ', 'imm', 'infl', 'trade', 'fp', 'healthcare', 'crime']

for iss, suf in tqdm(zip(issues, issue_suffixes)):
    worksheet = spreadsheet.worksheet(f"approval_stats_{suf}")
    worksheet.clear()

    issue_df = pres_issue[pres_issue['issue'] == iss]
    set_with_dataframe(worksheet, issue_df.reset_index())

7it [00:06,  1.16it/s]

In [110]:
## Net issue approval
net_issues = pd.pivot_table(pres_issue[pres_issue['issue'].isin(issues)], 
                            values=['net', 'net_lower_ci', 'net_upper_ci'], index=['end_date'], columns=['issue'],
                           aggfunc="first").reset_index()
net_issues.columns = ['_'.join(col).strip() for col in net_issues.columns.values]
net_issues.head()

,end_date_,net_crime,net_economy,net_foreign_policy,net_healthcare,net_immigration,net_inflation,net_trade_tariffs,net_lower_ci_crime,net_lower_ci_economy,...,net_lower_ci_immigration,net_lower_ci_inflation,net_lower_ci_trade_tariffs,net_upper_ci_crime,net_upper_ci_economy,net_upper_ci_foreign_policy,net_upper_ci_healthcare,net_upper_ci_immigration,net_upper_ci_inflation,net_upper_ci_trade_tariffs
0,2025-01-21,0.0,7.257911,3.257911,0.000000,9.257911,-4.742089,-0.742089,0.0,7.257911,...,9.257911,-4.742089,-0.742089,0.0,7.257911,3.257911,0.000000,9.257911,-4.742089,-0.742089
1,2025-01-22,0.0,7.257911,3.257911,0.000000,9.257911,-4.742089,-0.742089,0.0,7.257911,...,9.257911,-4.742089,-0.742089,0.0,7.257911,3.257911,0.000000,9.257911,-4.742089,-0.742089
2,2025-01-23,0.0,0.966241,3.257911,-15.556696,1.538686,-4.742089,-0.742089,0.0,-6.842702,...,-8.042076,-4.742089,-0.742089,0.0,8.775184,3.257911,-15.556696,11.119447,-4.742089,-0.742089
3,2025-01-24,0.0,0.966241,3.257911,-15.556696,1.538686,-4.742089,-0.742089,0.0,-6.842702,...,-8.042076,-4.742089,-0.742089,0.0,8.775184,3.257911,-15.556696,11.119447,-4.742089,-0.742089
4,2025-01-25,0.0,0.966241,3.257911,-15.556696,1.538686,-4.742089,-0.742089,0.0,-6.842702,...,-8.042076,-4.742089,-0.742089,0.0,8.775184,3.257911,-15.556696,11.119447,-4.742089,-0.742089

In [111]:
worksheet = spreadsheet.worksheet("net_approval_issues")
worksheet.clear()

set_with_dataframe(worksheet, net_issues.reset_index())

In [112]:
worksheet = spreadsheet.worksheet("generic_ballot_stats")
worksheet.clear()

set_with_dataframe(worksheet, generic_ballot.reset_index())

In [113]:
worksheet = spreadsheet.worksheet("ca_gov_primary_2026_average")
worksheet.clear()

set_with_dataframe(worksheet, ca_gov_primary)

## Polls Display Tables

In [114]:
pres_polls['sponsors'] = '^Sponsor: ' + pres_polls['sponsors'] + '^'
pres_polls['sponsors'] = pres_polls['sponsors'].fillna('')
pres_polls['partisan'] = pres_polls['partisan'].replace({
    'DEM': ' (D)',
    'REP': ' (R)',
    'WFP': ' (WF)'
}).fillna('')
pres_polls = pres_polls.sort_values(['total_weight'], ascending=False)
pres_polls = pres_polls.rename({
    'pollster':'Pollster', 'approve':'Approve', 'disapprove':'Disapprove', 'net':'Net', 
    'total_weight':'Weight', 'start_date':'Start Date', 'end_date':'End Date', 'url':'URL', 'adj_net':'Adjusted Net'}, axis='columns')
pres_polls['Sample'] = pres_polls['sample_size'].astype(int).astype(str) + ' ' + pres_polls['population']
pres_polls['Start Date'] = pd.to_datetime(pres_polls['Start Date']).astype(str)
pres_polls['End Date'] = pres_polls['End Date'].astype(str)
pres_polls = pres_polls.reset_index()
pres_polls['Pollster'] = ('<a href="' + pres_polls['URL'] + '" style="color:black; text-decoration:underline;"><u>' + 
                          pres_polls['Pollster'] + pres_polls['partisan'] + '</u></a>' + pres_polls['sponsors'])
pres_polls = pres_polls[['Pollster', 'Start Date', 'End Date', 'Sample', 'Weight', 'Approve', 'Disapprove', 'Net', 'Adjusted Net']]
pres_polls

,Pollster,Start Date,End Date,Sample,Weight,Approve,Disapprove,Net,Adjusted Net
0,"<a href=""https://napolitannews.org/jobapproval...",2026-03-18,2026-03-26,3000 RV,8.323113e-02,45.0,54.0,-9.0,-18.911419
1,"<a href=""https://www.foxnews.com/politics/fox-...",2026-03-20,2026-03-23,1001 RV,7.681155e-02,41.0,59.0,-18.0,-19.519114
2,"<a href=""https://poll.qu.edu/poll-release?rele...",2026-03-19,2026-03-23,1191 RV,7.634947e-02,38.0,56.0,-18.0,-14.509614
3,"<a href=""https://www.ipsos.com/en-us/economy-a...",2026-03-20,2026-03-23,1272 A,4.782438e-02,36.0,61.0,-25.0,-21.174009
4,"<a href=""https://jlpartners.com/nationwide-reg...",2026-03-18,2026-03-20,1037 RV,4.603054e-02,39.0,53.0,-14.0,-21.068624
...,...,...,...,...,...,...,...,...,...
680,"<a href=""https://mclaughlinonline.com/pols/wp-...",2025-01-22,2025-01-27,1000 LV,6.273108e-23,52.0,43.0,9.0,4.890718
681,"<a href=""https://substack.com/inbox/post/15539...",2025-01-21,2025-01-21,742 A,4.847648e-23,49.0,36.0,13.0,8.326841
682,"<a href=""https://quantusinsights.org/f/februar...",2025-02-01,2025-02-03,1000 RV,4.459723e-23,51.9,45.3,6.6,0.038018
683,"<a href=""https://www.ipsos.com/en-us/reuters-i...",2025-01-20,2025-01-21,1077 A,4.397274e-23,47.0,41.0,6.0,9.825991
684,"<a href=""https://quantusinsights.org/f/trump%E...",2025-01-22,2025-01-23,1000 RV,1.335052e-23,54.0,40.0,14.0,7.438018

In [115]:
worksheet = spreadsheet.worksheet("polls_display_table")
worksheet.clear()

set_with_dataframe(worksheet, pres_polls)

In [116]:
issue_polls['sponsor'] = '^Sponsor: ' + issue_polls['sponsor'] + '^'
issue_polls['sponsor'] = issue_polls['sponsor'].fillna('')
issue_polls = issue_polls.sort_values(['issue', 'total_weight'], ascending=[True, False])
issue_polls = issue_polls.rename({
    'pollster':'Pollster', 'approve':'Approve', 'disapprove':'Disapprove', 'net':'Net', 
    'total_weight':'Weight', 'start_date':'Start Date', 'end_date':'End Date', 'url':'URL', 'adj_net':'Adjusted Net',
    'issue':'Issue'}, axis='columns')
issue_polls['Sample'] = issue_polls['sample_size'].astype(int).astype(str) + ' ' + issue_polls['population']
issue_polls['Start Date'] = pd.to_datetime(issue_polls['Start Date']).astype(str)
issue_polls['End Date'] = issue_polls['End Date'].astype(str)
issue_polls = issue_polls.reset_index()
issue_polls['Pollster'] = ('<a href="' + issue_polls['URL'] + '" style="color:black; text-decoration:underline;"><u>' + 
                          issue_polls['Pollster'] + '</u></a>' + issue_polls['sponsor'])
issue_polls = issue_polls[issue_polls['Issue'].isin(issues)]
issue_polls['Issue'] = issue_polls['Issue'].replace({
    'economy': 'Economy',
    'immigration': 'Immigration',
    'foreign_policy': 'Foreign policy',
    'inflation': 'Inflation/prices',
    'trade_tariffs': 'Trade/tariffs',
    'healthcare': 'Healthcare',
    'crime': 'Crime'
})
issue_polls = issue_polls[['Pollster', 'Start Date', 'End Date', 'Issue', 'Sample', 'Weight', 'Approve', 'Disapprove', 'Net', 'Adjusted Net']]
issue_polls

,Pollster,Start Date,End Date,Issue,Sample,Weight,Approve,Disapprove,Net,Adjusted Net
0,"<a href=""https://www.ipsos.com/en-us/economy-a...",2026-03-20,2026-03-23,Crime,1272 A,1.256549e-02,39.0,49.0,-10.0,-8.742089
1,"<a href=""https://www.ipsos.com/en-us/americans...",2026-03-17,2026-03-19,Crime,1545 A,1.018748e-02,42.0,47.0,-5.0,-3.742089
2,"<a href=""https://napolitannews.org/posts/trump...",2026-03-16,2026-03-19,Crime,1000 RV,8.186728e-03,49.0,48.0,1.0,-7.826693
3,"<a href=""https://d3nkl3psvxxpe9.cloudfront.net...",2026-03-13,2026-03-16,Crime,1595 A,5.504009e-03,43.0,47.0,-4.0,-6.427371
4,"<a href=""https://www.gelliottmorris.com/p/2026...",2026-03-16,2026-03-18,Crime,1530 A,2.875434e-03,42.0,52.0,-10.0,-10.115606
...,...,...,...,...,...,...,...,...,...,...
1368,"<a href=""https://pro.morningconsult.com/tracke...",2025-02-07,2025-02-09,Trade/tariffs,22305 RV,1.308496e-16,47.0,43.0,4.0,-10.861140
1369,"<a href=""https://www.dataforprogress.org/memos...",2025-01-31,2025-02-02,Trade/tariffs,1205 LV,7.023958e-17,42.0,46.0,-4.0,-8.939518
1370,"<a href=""https://pro.morningconsult.com/tracke...",2025-01-31,2025-02-03,Trade/tariffs,2303 RV,5.603176e-17,48.0,40.0,8.0,-6.861140
1371,"<a href=""https://pro.morningconsult.com/tracke...",2025-01-24,2025-01-26,Trade/tariffs,2302 RV,3.031610e-17,50.0,37.0,13.0,-1.861140
1372,"<a href=""https://www.ipsos.com/en-us/reuters-i...",2025-01-20,2025-01-21,Trade/tariffs,1077 A,1.715399e-17,38.0,40.0,-2.0,-0.742089

In [118]:
worksheet = spreadsheet.worksheet("polls_display_issues")
worksheet.clear()

set_with_dataframe(worksheet, issue_polls)

APIError: APIError: [429]: Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:382361870111'.

In [ ]:
gb_polls['sponsors'] = '^Sponsor: ' + gb_polls['sponsors'] + '^'
gb_polls['partisan'] = gb_polls['partisan'].replace({
    'DEM': ' (D)',
    'REP': ' (R)',
    'WFP': ' (WF)'
}).fillna('')
gb_polls['sponsors'] = gb_polls['sponsors'].fillna('')
gb_polls = gb_polls.sort_values(['total_weight'], ascending=False)
gb_polls = gb_polls.rename({
    'pollster':'Pollster', 'dem':'Democrats', 'rep':'Republicans', 'net':'Net', 
    'total_weight':'Weight', 'start_date':'Start Date', 'end_date':'End Date', 'url':'URL', 'adj_net':'Adjusted Net'}, axis='columns')
gb_polls['Sample'] = gb_polls['sample_size'].astype(int).astype(str) + ' ' + gb_polls['population']
gb_polls['Start Date'] = pd.to_datetime(gb_polls['Start Date']).astype(str)
gb_polls['End Date'] = gb_polls['End Date'].astype(str)
gb_polls = gb_polls.reset_index()
gb_polls['Pollster'] = ('<a href="' + gb_polls['URL'] + '" style="color:black; text-decoration:underline;"><u>' + 
                          gb_polls['Pollster'] + gb_polls['partisan'] + '</u></a>' + gb_polls['sponsors'])
gb_polls = gb_polls[['Pollster', 'Start Date', 'End Date', 'Sample', 'Weight', 'Democrats', 'Republicans', 'Net', 'Adjusted Net']]
gb_polls

In [ ]:
worksheet = spreadsheet.worksheet("generic_ballot_polls_display_table")
worksheet.clear()

set_with_dataframe(worksheet, gb_polls)

In [ ]:
ca_gov_polls = ca_gov_polls[['pollster', 'sponsors', 'sponsor_candidate', 'start_date', 'end_date', 'sample_size', 'population',
                            'url', 'partisan', 'internal', 'antonio_ramon_villaraigosa_dem', 'steve_hilton_rep', 'katie_porter_dem',
       'chad_bianco_rep', 'xavier_becerra_dem', 'tom_steyer_dem', 'eric_swalwell_dem', 'matt_mahan_dem', 'total_weight']]
ca_gov_polls['sponsors'] = '^Sponsor: ' + ca_gov_polls['sponsors'] + '^'
ca_gov_polls['sponsor_candidate'] = '^' + ca_gov_polls['sponsor_candidate'] + ' internal^'
ca_gov_polls['partisan'] = ca_gov_polls['partisan'].replace({
    'DEM': ' <p style="color: blue">(D)</p>',
    'REP': ' <p style="color: red">(R)</p>'
}).fillna('')
ca_gov_polls['sponsors'] = ca_gov_polls['sponsors'].fillna('')
ca_gov_polls['sponsor_candidate'] = ca_gov_polls['sponsor_candidate'].fillna('')
ca_gov_polls = ca_gov_polls.sort_values(by=['total_weight'], ascending=False)
ca_gov_polls = ca_gov_polls.rename({
    'pollster': 'Pollster',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'antonio_ramon_villaraigosa_dem': 'Villaraigosa', 'steve_hilton_rep': 'Hilton', 'katie_porter_dem': 'Porter',
    'chad_bianco_rep': 'Bianco', 'xavier_becerra_dem': 'Becerra', 'tom_steyer_dem': 'Steyer', 'eric_swalwell_dem': 'Swalwell', 
    'matt_mahan_dem': 'Mahan',
    'total_weight': 'Weight', 'url': 'URL'
}, axis='columns')
ca_gov_polls['sample_size'] = ca_gov_polls['sample_size'].fillna(0).astype(int).replace({0: ''}).astype(str) + ' '
ca_gov_polls['Sample'] = ca_gov_polls['sample_size'] + ca_gov_polls['population']
ca_gov_polls['Start Date'] = pd.to_datetime(ca_gov_polls['Start Date']).astype(str)
ca_gov_polls['End Date'] = pd.to_datetime(ca_gov_polls['End Date']).astype(str)
ca_gov_polls = ca_gov_polls.reset_index()
ca_gov_polls['Pollster'] = ('<a href="' + ca_gov_polls['URL'] + '" style="color:black; text-decoration:underline;"><u>' + 
                          ca_gov_polls['Pollster'] + '</u></a>' + ca_gov_polls['partisan'] + ca_gov_polls['sponsors'] + 
                            ca_gov_polls['sponsor_candidate'])
ca_gov_polls = ca_gov_polls[['Pollster', 'Start Date', 'End Date', 'Sample', 'Weight', 'Porter', 'Hilton', 'Bianco', 'Swalwell', 'Steyer',
                            'Becerra', 'Villaraigosa', 'Mahan']]
ca_gov_polls

In [ ]:
worksheet = spreadsheet.worksheet("ca_gov_primary_26_polls")
worksheet.clear()

set_with_dataframe(worksheet, ca_gov_polls)

## Poll Average Chart (Test)

In [ ]:
pres.head()

In [ ]:
disappr_ci_hex = "#e86eaf",
appr_ci_hex = "#60be65"
disappr_ci_rgba = "rgba(232, 110, 175, 0.3)"
appr_ci_rgba = "rgba(96, 190, 101, 0.3)"
grid_col = "#d4d2d2"


# Approve
fig = go.Figure(go.Scatter(
    x=pres['end_date'],
    y=pres['approve'],
    hovertemplate="%{y:.2f}%",
    name="<b>Approve</b>",
    line=dict(color="#228833"),
    showlegend=False
))

# Disapprove
fig.add_trace(go.Scatter(
    x=pres['end_date'],
    y=pres['disapprove'],
    hovertemplate="%{y:.2f}%",
    name="<b>Disapprove</b>",
    line=dict(color="#aa3377"),
    showlegend=False
    )
)

# Approve CI
fig.add_traces([

    # Upper bound
    go.Scatter(
        x=pres['end_date'],
        y=pres['approve_upper_ci'],
        marker=dict(color=appr_ci_hex),
        line=dict(width=0),
        mode='lines',
        showlegend=False,
        hoverinfo="skip"
    ),

    # Lower bound
    go.Scatter(
        x=pres['end_date'],
        y=pres['approve_lower_ci'],
        marker=dict(color=appr_ci_hex),
        line=dict(width=0),
        mode='lines',
        fillcolor=appr_ci_rgba,
        fill="tonexty",
        showlegend=False,
        hoverinfo="skip"
    )
])

# Disapprove CI
fig.add_traces([

    # Upper bound
    go.Scatter(
        x=pres['end_date'],
        y=pres['disapprove_upper_ci'],
        marker=dict(color=disappr_ci_hex),
        line=dict(width=0),
        mode='lines',
        showlegend=False,
        hoverinfo="skip"
    ),

    # Lower bound
    go.Scatter(
        x=pres['end_date'],
        y=pres['disapprove_lower_ci'],
        marker=dict(color=disappr_ci_hex),
        line=dict(width=0),
        mode='lines',
        fillcolor=disappr_ci_rgba,
        fill="tonexty",
        showlegend=False,
        hoverinfo="skip"
    )
])

fig.update_layout(
    title=dict(text="Trump's Second Term Presidential Approval"),
    hovermode="x"
)

fig.update_xaxes(gridcolor=grid_col)
fig.update_yaxes(gridcolor=grid_col)

fig.update_layout(hovermode="x", hoverlabel_align="right", plot_bgcolor="rgba(0, 0, 0, 0)", height=500)
fig.show()